// Shared layout for Xender commercial pages (XEND-DEV-002). Pages are generated by
// scripts/build-commercial-pages.mjs so header, footer, lead form and design stay single-sourced.
export const SITE = "https://www.xendersecrets.com";
export const WA_NUMBER = "919821941814";
export const EMAIL = "Sahilsharma171098@gmail.com";

export const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
export const wa = (text) => `https://wa.me/${WA_NUMBER}?text=${encodeURIComponent(text)}`;

/** Approved 2026-10-06: package prices are exclusive of 18% GST (Xender is GST-registered). */
export const GST_RATE = 0.18;
export const inr = (n) => "₹" + Number(n).toLocaleString("en-IN", { minimumFractionDigits: Number.isInteger(n) ? 0 : 2, maximumFractionDigits: 2 });
/** 999 → "₹1,178.82" (base + 18% GST, rounded to paise). */
export const inclGst = (base) => inr(Math.round(base * (1 + GST_RATE) * 100) / 100);

export const OFFERS = [
  { id: "free-website-check", name: "Free website check", price: "₹0", unit: "", short: "Free website check" },
  { id: "founding-website-999", name: "Founding Website", price: "₹999", base: 999, unit: "one-time", short: "₹999 + GST · Founding Website (1 page)" },
  { id: "business-starter-1999", name: "Business Starter", price: "₹1,999", base: 1999, unit: "one-time", short: "₹1,999 + GST · Business Starter (3 pages)" },
  { id: "business-pro-3499", name: "Business Pro", price: "₹3,499", base: 3499, unit: "one-time", short: "₹3,499 + GST · Business Pro (5 pages)" },
  { id: "redesign", short: "Redesign my existing website" },
  { id: "custom-build", short: "Custom build / automation" },
  { id: "not-sure", short: "Not sure yet" },
];
export const offerById = (id) => OFFERS.find((o) => o.id === id);

const NAV = [
  ["/services.html", "Pricing"],
  ["/website-catalog.html", "Work"],
  ["/services.html#industries", "Industries"],
  ["/articles.html", "Guides"],
  ["/about.html", "About"],
  ["/novels.html", "Novels"],
];

export function header({ home = false } = {}) {
  const nav = home
    ? [["/services.html", "Pricing"], ["/website-catalog.html", "Work"], ["#process", "How it works"], ["/articles.html", "Guides"], ["/about.html", "About"], ["#faq", "FAQ"]]
    : NAV;
  return `<a class="skip" href="#main">Skip to content</a>
  <header class="site-header">
    <div class="wrap header-inner">
      <a class="brand" href="/" aria-label="Xender Secrets home">XENDER <span>SECRETS</span></a>
      <nav class="nav" id="nav" aria-label="Main">
        ${nav.map(([href, label]) => `<a href="${href}">${label}</a>`).join("\n        ")}
      </nav>
      <div class="header-actions">
        <button class="icon-btn" id="themeToggle" type="button" aria-label="Switch to dark mode">◐</button>
        <a class="btn primary header-cta" href="#start" data-cta="header-free-check">Free website check</a>
        <button class="icon-btn menu" id="menu" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="nav">☰</button>
      </div>
    </div>
  </header>`;
}

export function footer() {
  return `<footer class="site-footer">
    <div class="wrap footer-inner">
      <div>
        <strong>XENDER SECRETS</strong><br>
        Founded by Sahil Kumar Sharma · Gurugram, Haryana, India<br>
        GSTIN: 06IQFPS4456B1ZP · Udyam (MSME): <a href="https://udyamregistration.gov.in/Udyam_Verify.aspx" target="_blank" rel="noopener">UDYAM-HR-05-0152992</a>
      </div>
      <nav class="footer-links" aria-label="Footer">
        <a href="/services.html">Pricing</a>
        <a href="/website-catalog.html">Work</a>
        <a href="/business-templates.html">Templates</a>
        <a href="/website-cost-calculator.html">Cost calculator</a>
        <a href="/sitecheck.html">SiteCheck extension</a>
        <a href="/articles.html">Articles</a>
        <a href="/about.html">About</a>
        <a href="/contact.html">Contact</a>
        <a href="/privacy.html">Privacy</a>
        <a href="/terms.html">Terms</a>
        <a href="/refund.html">Refunds</a>
      </nav>
    </div>
    <div class="wrap footer-industries">
      <span>Websites for:</span>
      <a href="/accountant-website-development.html">CA firms</a>
      <a href="/clinic-website-development.html">Clinics &amp; dentists</a>
      <a href="/real-estate-website-development.html">Real estate</a>
      <a href="/recruitment-agency-website-development.html">Recruitment</a>
      <a href="/consultant-website-development.html">Consultants</a>
      <a href="/coaching-website-development.html">Coaching</a>
      <a href="/gym-website-development.html">Gyms</a>
      <a href="/restaurant-website-development.html">Restaurants</a>
    </div>
    <div class="wrap footer-industries">
      <span>Website development in:</span>
      <a href="/website-development-gurugram.html">Gurgaon (Gurugram)</a>
      <a href="/website-development-delhi.html">Delhi NCR</a>
      <a href="/website-development-noida.html">Noida</a>
      <a href="/small-business-website-india.html">All of India</a>
    </div>
  </footer>`;
}

/** The lead form. `cta` labels the form in analytics; `offer` preselects the dropdown. */
export function leadForm({ cta, offer = "free-website-check", heading, intro, waText, bullets }) {
  const id = (s) => `lf-${s}`;
  return `<section id="start" class="section start">
      <div class="wrap split">
        <div>
          <p class="kicker">Start here</p>
          <h2>${heading || "Get your free website check <span>or a quote.</span>"}</h2>
          <p>${intro || "Tell us a little about your business. We reply personally, usually on WhatsApp — no newsletters, no spam."}</p>
          <ul class="checks">${(bullets || ["Specific fixes for your current site", "A fixed-price quote if you want us to build", "No obligation"]).map((b) => `<li>${b}</li>`).join("")}</ul>
          <p class="alt-contact">Prefer to talk? <a href="${esc(wa(waText || "Hi Xender Secrets, I want to discuss a website."))}" data-cta="start-whatsapp" target="_blank" rel="noopener">WhatsApp +91 98219 41814</a> · <a href="mailto:${EMAIL}" data-cta="start-email">Email us</a></p>
        </div>
        <form class="card lead-form" data-lead-form data-cta="${esc(cta)}" novalidate>
          <div class="field">
            <label for="${id("name")}">Your name *</label>
            <input id="${id("name")}" name="name" autocomplete="name" required maxlength="80">
          </div>
          <div class="field-row">
            <div class="field">
              <label for="${id("phone")}">WhatsApp number</label>
              <input id="${id("phone")}" name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="98xxxxxxxx" maxlength="20">
            </div>
            <div class="field">
              <label for="${id("email")}">Email</label>
              <input id="${id("email")}" name="email" type="email" autocomplete="email" maxlength="254">
            </div>
          </div>
          <p class="hint">WhatsApp number or email — at least one, so we can reply.</p>
          <div class="field">
            <label for="${id("business")}">Business name &amp; city</label>
            <input id="${id("business")}" name="business" autocomplete="organization" maxlength="120" placeholder="e.g. Sharma Dental, Gurugram">
          </div>
          <div class="field">
            <label for="${id("website")}">Current website or Instagram / Google page <span class="opt">(optional)</span></label>
            <input id="${id("website")}" name="website" inputmode="url" maxlength="300" placeholder="yourbusiness.com">
          </div>
          <div class="field">
            <label for="${id("offer")}">What do you need?</label>
            <select id="${id("offer")}" name="offer">
              ${OFFERS.map((o) => `<option value="${o.id}"${o.id === offer ? " selected" : ""}>${esc(o.short)}</option>`).join("\n              ")}
            </select>
          </div>
          <div class="field">
            <label for="${id("message")}">Anything we should know? <span class="opt">(optional)</span></label>
            <textarea id="${id("message")}" name="message" rows="3" maxlength="1500" placeholder="What do you sell, and who are your customers?"></textarea>
          </div>
          <div class="hp" aria-hidden="true"><label for="${id("company-url")}">Leave this empty</label><input id="${id("company-url")}" name="company_url" tabindex="-1" autocomplete="off"></div>
          <button class="btn primary block lg" type="submit">Send — we'll reply personally</button>
          <p class="status" data-lead-status role="alert" aria-live="polite"></p>
          <p class="fine">By sending, you agree we may contact you about this enquiry. See our <a href="/privacy.html">privacy policy</a>.</p>
        </form>
      </div>
    </section>`;
}

export function faqBlock(items, { heading = 'Before you <span>decide.</span>' } = {}) {
  return `<section id="faq" class="section">
      <div class="wrap narrow">
        <div class="section-head">
          <p class="kicker">Questions</p>
          <h2>${heading}</h2>
        </div>
        <div class="faq">
          ${items.map(([q, a]) => `<details><summary>${esc(q)}</summary><p>${a}</p></details>`).join("\n          ")}
        </div>
      </div>
    </section>`;
}

const strip = (html) => String(html).replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/&#39;/g, "'").replace(/&quot;/g, '"').replace(/\s+/g, " ").trim();

export function faqJsonLd(items) {
  return { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: items.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: strip(a) } })) };
}

export const ORG_ID = SITE + "/#business";
export const ORG_JSONLD = {
  "@context": "https://schema.org", "@type": "ProfessionalService", "@id": ORG_ID, name: "Xender Secrets", url: SITE + "/",
  image: SITE + "/og-xender.png", logo: { "@type": "ImageObject", url: SITE + "/og-xender.png" }, email: EMAIL,
  description: "Business websites, landing pages and website redesigns for small businesses.",
  founder: { "@type": "Person", name: "Sahil Kumar Sharma", sameAs: ["https://www.startupindia.gov.in/bhaskar/profile?bhaskarid=IN-1026-9552QE", "https://www.linkedin.com/in/sahilkumarsharma-operations"] }, areaServed: ["IN", "GB", "US", "CA"],
  telephone: "+91-9821941814", address: { "@type": "PostalAddress", addressLocality: "Gurugram", addressRegion: "Haryana", addressCountry: "IN" },
  priceRange: "₹999–₹4,999+ (+18% GST)",
};

export function breadcrumbJsonLd(trail) {
  return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: trail.map(([name, path], i) => ({ "@type": "ListItem", position: i + 1, name, item: canonicalUrl(path) })) };
}

/**
 * Service schema for an industry or location page. Only facts we can stand behind: the
 * provider, where we work and the published package prices (exclusive of GST). No ratings,
 * reviews or client claims (docs/REVENUE_ARCHITECTURE.md copy rules).
 */
export function serviceJsonLd({ path, name, serviceType, description, areaServed, audience }) {
  return {
    "@context": "https://schema.org", "@type": "Service", name, serviceType, description,
    url: canonicalUrl(path), provider: { "@id": ORG_ID }, areaServed,
    ...(audience ? { audience: { "@type": "BusinessAudience", audienceType: audience } } : {}),
    offers: { "@type": "AggregateOffer", priceCurrency: "INR", lowPrice: "999", highPrice: "3499", offerCount: "3",
      description: "Fixed-price website packages; prices exclude 18% GST." },
  };
}

/** /page.html → https://www.xendersecrets.com/page (the URL Cloudflare serves with 200). */
export function canonicalUrl(path) {
  const p = path.split(/[?#]/)[0];
  return SITE + (p === "/" || p === "/index.html" ? "/" : p.replace(/\.html$/, ""));
}

/**
 * Cloudflare assets (html_handling: auto-trailing-slash) answer /page.html with a 307 to /page.
 * Internal links therefore point at the final URL so crawlers never spend a hop on a redirect
 * and every link agrees with the page's canonical. Applies to root-relative hrefs only.
 */
export function cleanLinks(html) {
  return html
    .replace(/href="\/index\.html(?=[?#"])/g, 'href="/')
    .replace(/href="\/([a-z0-9][a-z0-9-]*)\.html(?=[?#"])/g, 'href="/$1');
}

/** Full HTML document. */
export function page({ path, title, description, ogTitle, body, jsonld = [], home = false, robots = "index,follow", ogType = "website" }) {
  // Cloudflare assets (html_handling: auto-trailing-slash) 307-redirect /page.html → /page, so
  // canonical URLs use the final extensionless form.
  const canonical = canonicalUrl(path);
  const ld = jsonld.map((j) => `<script type="application/ld+json">${JSON.stringify(j)}</script>`).join("\n  ");
  return cleanLinks(`<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}">
  <link rel="canonical" href="${canonical}">
  <meta name="robots" content="${robots}">
  <meta name="theme-color" content="#ffffff">
  <meta property="og:type" content="${ogType}">
  <meta property="og:site_name" content="Xender Secrets">
  <meta property="og:title" content="${esc(ogTitle || title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${SITE}/og-xender.png">
  <meta name="twitter:card" content="summary_large_image">
  <script>try{if(localStorage.getItem("xs-theme")==="dark")document.documentElement.dataset.theme="dark"}catch(e){}</script>
  <link rel="stylesheet" href="/home.css">
  ${ld}
</head>
<body>
  ${header({ home })}

  <main id="main">
    ${body}
  </main>

  ${footer()}

  <a class="wa-float" href="${esc(wa("Hi Xender Secrets, I want a website for my business."))}" data-cta="float-whatsapp" target="_blank" rel="noopener" aria-label="Chat on WhatsApp">WhatsApp</a>

  <script src="/home.js" defer></script>
  <script src="/xs-growth.js" defer></script>
</body>
</html>
`);
}
