// Check catalog for Xender SiteCheck: one entry per check id returned by src/audit.js.
// weight: 3 = critical, 2 = warning, 1 = recommendation (heuristic). See extension/docs/SCORING.md.
// Copy rules: plain language, say why it matters and what to do; never overstate.

export const CATEGORIES = [
  { id: "seo", label: "SEO", weight: 25 },
  { id: "accessibility", label: "Accessibility", weight: 25 },
  { id: "usability", label: "Usability", weight: 15 },
  { id: "conversion", label: "Conversion", weight: 20 },
  { id: "technical", label: "Technical", weight: 15 },
];

export const SEVERITY = { 3: "critical", 2: "warning", 1: "recommendation" };

const c = (id, category, weight, title, passTitle, why, fix) => ({ id, category, weight, title, passTitle, why, fix });

export const CHECKS = [
  // SEO
  c("seo-title-missing", "seo", 3, "Page title is missing", "Page has a title",
    "The title is the clickable headline in search results and the label on the browser tab. Without one, search engines and visitors have to guess what the page is.",
    "Add a <title> that names the page and the business, e.g. “Dental Clinic in Gurugram | Smile Care”."),
  c("seo-title-quality", "seo", 2, "Page title is weak or the wrong length", "Page title length looks right",
    "Very short or generic titles (“Home”) don't tell searchers why to click; very long titles are cut off in search results.",
    "Write a specific title of roughly 15–65 characters: what the page offers + brand name."),
  c("seo-description-missing", "seo", 2, "Meta description is missing", "Meta description is present",
    "Search engines may generate an unpredictable snippet from random page text.",
    "Add a concise, page-specific <meta name=\"description\"> that says what the visitor gets."),
  c("seo-description-length", "seo", 1, "Meta description length could be better", "Meta description length looks right",
    "Descriptions that are very short waste the space; very long ones get cut off.",
    "Aim for about 70–160 characters written for people, with a reason to click."),
  c("seo-canonical", "seo", 2, "Canonical URL is missing", "Canonical URL is set",
    "When the same page is reachable at several URLs (with tracking parameters, with or without “www”), a canonical tag tells search engines which one to show.",
    "Add <link rel=\"canonical\" href=\"https://…\"> with this page's preferred full URL."),
  c("seo-viewport", "seo", 3, "Mobile viewport tag is missing", "Mobile viewport is configured",
    "Without it, phones render the page as a shrunken desktop site. Most small-business visitors are on mobile.",
    "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">."),
  c("seo-og-title", "seo", 1, "Open Graph title is missing", "Open Graph title is set",
    "When the page is shared on WhatsApp, LinkedIn or Facebook, the preview may show the wrong headline.",
    "Add <meta property=\"og:title\" content=\"…\">."),
  c("seo-og-description", "seo", 1, "Open Graph description is missing", "Open Graph description is set",
    "Shared links may appear without a summary, which lowers clicks.",
    "Add <meta property=\"og:description\" content=\"…\">."),
  c("seo-og-image", "seo", 1, "Open Graph image is missing", "Open Graph image is set",
    "Links shared on social apps and messengers show no picture, or a random one.",
    "Add <meta property=\"og:image\" content=\"https://…/share.png\"> (a full https URL, ideally 1200×630)."),
  c("seo-noindex", "seo", 2, "Page asks search engines not to index it", "Page allows search indexing",
    "A “noindex” robots tag keeps this page out of search results. That is right for private pages and a serious mistake for public ones.",
    "If this page should be found on Google, remove “noindex” from the robots meta tag."),
  c("seo-h1-missing", "seo", 3, "No H1 heading", "Page has an H1 heading",
    "The main heading tells visitors, screen readers and search engines what the page is about.",
    "Mark the page's main headline up as a single <h1>."),
  c("seo-h1-multiple", "seo", 1, "More than one H1 heading", "One H1 heading",
    "Several H1s can blur what the page's main topic is. Not an error, but one clear H1 is easier to understand.",
    "Keep one H1 for the main headline and use H2/H3 for sections."),

  // Accessibility
  c("a11y-html-lang", "accessibility", 2, "Page language is not declared", "Page language is declared",
    "Screen readers use it to pick the right pronunciation; browsers use it for translation.",
    "Add a lang attribute, e.g. <html lang=\"en\">."),
  c("a11y-zoom-disabled", "accessibility", 2, "Zoom is disabled on mobile", "Zoom is allowed",
    "Blocking pinch-zoom makes text unreadable for people with low vision.",
    "Remove user-scalable=no and any maximum-scale below 2 from the viewport tag."),
  c("a11y-img-alt", "accessibility", 3, "Images without alt text", "Images have alt attributes",
    "Screen readers can't describe these images, and search engines can't understand them.",
    "Add alt text that describes each meaningful image; use alt=\"\" only for purely decorative ones."),
  c("a11y-img-empty-alt", "accessibility", 1, "Large images marked as decorative", "No large images hidden from screen readers",
    "alt=\"\" hides an image from screen readers. That's right for decoration, but large images often carry meaning (products, people, places).",
    "Check these images: if they convey information, describe it in the alt text."),
  c("a11y-link-name", "accessibility", 3, "Links with no text", "All links have text",
    "Icon-only or empty links are announced as just “link”, so people can't tell where they go.",
    "Add visible text, or an aria-label (e.g. aria-label=\"Instagram\") to icon links."),
  c("a11y-link-vague", "accessibility", 1, "Vague link text", "Link text is descriptive",
    "“Click here” and “Read more” make no sense out of context — screen-reader users often list links on their own.",
    "Say where the link goes: “Read the pricing guide” instead of “Read more”."),
  c("a11y-button-name", "accessibility", 3, "Buttons without an accessible name", "All buttons have names",
    "A button without text or a label is announced as just “button”; people can't tell what it does.",
    "Add visible text or an aria-label to icon buttons (menu, close, search…)."),
  c("a11y-form-labels", "accessibility", 3, "Form fields without labels", "Form fields are labelled",
    "Without a label, screen readers can't say what to type. Placeholder text disappears as soon as someone starts typing.",
    "Give every field a <label for=\"…\">, or an aria-label if a visible label truly isn't possible."),
  c("a11y-empty-heading", "accessibility", 2, "Empty headings", "No empty headings",
    "Empty headings appear in screen-reader heading lists as blank entries.",
    "Remove empty heading tags or put the heading text inside them."),
  c("a11y-heading-order", "accessibility", 2, "Heading levels are skipped", "Heading levels are in order",
    "Jumping from H2 to H4 makes the page outline confusing for screen-reader and keyboard users.",
    "Use heading levels in order (H1 → H2 → H3); style them with CSS rather than picking a level for its size."),
  c("a11y-aria", "accessibility", 2, "Invalid ARIA", "No ARIA problems detected",
    "Wrong roles, references to missing elements, or focusable items inside aria-hidden regions confuse assistive technology.",
    "Fix the role names and id references listed, and don't put focusable elements inside aria-hidden=\"true\"."),
  c("a11y-contrast", "accessibility", 2, "Low text contrast", "Text contrast meets WCAG AA where measured",
    "Light grey or low-contrast text is hard to read in sunlight and for people with low vision. Measured only where the background colour could be determined reliably.",
    "Darken the text or lighten the background until it meets 4.5:1 (3:1 for large text)."),

  // Usability
  c("ux-horizontal-overflow", "usability", 2, "Page scrolls sideways", "No sideways scrolling",
    "Content wider than the window makes visitors pan left and right — a common reason mobile visitors leave. Measured at your current window width.",
    "Find the wide element(s) listed and constrain them (max-width: 100%, flexible grids, wrapping long words)."),
  c("ux-form-submit", "usability", 2, "Form without a submit button", "Forms have submit buttons",
    "Visitors may not know how to send the form, and pressing Enter may not work.",
    "Add a clearly labelled <button type=\"submit\"> to every form."),
  c("ux-autocomplete", "usability", 1, "Contact fields without autocomplete", "Contact fields support autofill",
    "Autofill saves typing — especially on phones — and reduces typos in emails and numbers.",
    "Add autocomplete=\"name\", \"email\", \"tel\" etc. to the fields listed."),
  c("ux-input-types", "usability", 1, "Email/phone fields use a plain text keyboard", "Email/phone fields use the right keyboard",
    "type=\"email\" and type=\"tel\" show the right keyboard on phones and help browsers validate input.",
    "Use type=\"email\" for email fields and type=\"tel\" for phone numbers."),

  // Conversion (heuristics)
  c("cro-cta-present", "conversion", 2, "No clear call to action", "Clear call to action found",
    "Visitors need an obvious next step — book, call, get a quote, buy. Heuristic: we look for action words in links and buttons.",
    "Add one prominent action button that matches what you want visitors to do."),
  c("cro-cta-vague", "conversion", 1, "Generic submit button labels", "Submit buttons say what happens",
    "“Submit” says nothing about the result; specific labels tend to get more clicks.",
    "Name the outcome: “Get my free quote”, “Book appointment”, “Send enquiry”."),
  c("cro-cta-competing", "conversion", 1, "Many competing calls to action", "Calls to action are focused",
    "Several different buttons in the first screen can split attention. Heuristic, not a rule.",
    "Pick one primary action for the first screen and make the others secondary links."),
  c("cro-contact", "conversion", 2, "No visible contact method", "Contact method is visible",
    "Many visitors want to call, email or WhatsApp before they buy or book. Heuristic: we look for phone, email and WhatsApp links or text.",
    "Show a tap-to-call, email or WhatsApp link where visitors decide — usually the header and footer."),
  c("cro-trust", "conversion", 1, "No trust or policy links", "Trust and policy links found",
    "Links to About, Contact, Privacy or Refund pages reassure visitors that a real business stands behind the site.",
    "Link to your About, Contact and Privacy pages, usually in the footer."),
  c("cro-form-length", "conversion", 1, "Long form", "Forms are a reasonable length",
    "Every extra field is a reason to give up. Heuristic: forms with more than 8 fields are flagged.",
    "Ask only what you need for the first reply; collect the rest later."),
  c("cro-nav", "conversion", 1, "Crowded main navigation", "Main navigation is focused",
    "Too many top-level menu items make it harder to find the important pages. Heuristic: more than 10 visible links.",
    "Group or trim menu items so the key pages stand out."),
  c("cro-placeholder", "conversion", 2, "Placeholder text is visible", "No placeholder text found",
    "“Lorem ipsum” or “your text here” makes a site look unfinished and erodes trust.",
    "Replace placeholder copy with real content before visitors see it."),

  // Technical / security
  c("tech-https", "technical", 3, "Page is not served over HTTPS", "Page uses HTTPS",
    "Browsers label HTTP pages “Not secure”, and anything typed can be read or altered in transit.",
    "Enable HTTPS (most hosts offer free certificates) and redirect http:// to https://."),
  c("tech-password-http", "technical", 3, "Password field on an insecure page", "Password fields are on a secure page",
    "Passwords typed on an HTTP page are sent unencrypted.",
    "Serve this page over HTTPS before asking for passwords."),
  c("tech-mixed-content", "technical", 3, "Insecure resources on a secure page", "No insecure resources",
    "Browsers block or warn about http:// scripts, styles and images on https:// pages, which can break the page or show a warning.",
    "Load every resource over https:// (or a relative URL)."),
  c("tech-form-http", "technical", 3, "Form submits over insecure HTTP", "Forms submit securely",
    "Whatever visitors type into this form is sent unencrypted.",
    "Change the form action to an https:// address."),
  c("tech-dead-links", "technical", 2, "Links that don't go anywhere", "No empty or javascript: links",
    "Links with an empty, “#” or javascript: address do nothing without scripts, can't be opened in a new tab, and confuse keyboard and screen-reader users.",
    "Give each link a real destination, or use a <button> for actions."),
  c("tech-malformed-links", "technical", 2, "Mistyped link addresses", "Link addresses look valid",
    "Addresses like “htp://”, “www.example.com” without https://, or mailto: without an email address won't work as intended.",
    "Correct the listed addresses (include https:// for external sites)."),
  c("tech-broken-anchors", "technical", 2, "Broken same-page links", "Same-page links work",
    "These links jump to a section id that doesn't exist on this page, so clicking them does nothing. Verified locally on this page.",
    "Add the missing id to the target section, or fix the link."),
  c("tech-insecure-links", "technical", 1, "Links to insecure http:// pages", "No links to http:// pages",
    "Visitors following these links land on pages marked “Not secure”.",
    "Switch the links to https:// where the destination supports it."),
  c("tech-target-blank", "technical", 1, "New-tab links without rel=\"noopener\"", "New-tab links are safe",
    "Modern browsers already apply noopener by default; adding it protects visitors on older browsers from tab-hijacking.",
    "Add rel=\"noopener\" to links with target=\"_blank\"."),
  c("tech-doctype", "technical", 2, "Missing doctype (quirks mode)", "Standards mode doctype",
    "Without <!doctype html> browsers use legacy “quirks mode”, which can break layouts in subtle ways.",
    "Make <!doctype html> the very first line of the page."),
  c("tech-duplicate-ids", "technical", 1, "Duplicate element ids", "Element ids are unique",
    "Duplicate ids can break labels, same-page links and scripts that expect one element.",
    "Make each id unique on the page."),
  c("tech-dom-size", "technical", 1, "Very large page structure", "Page structure is a reasonable size",
    "Pages with thousands of elements or very deep nesting can feel slow on low-end phones. Flagged above 1,500 elements or 32 levels.",
    "Remove hidden or duplicated markup (e.g. separate mobile and desktop copies) and simplify deeply nested wrappers."),
  c("tech-oversized-images", "technical", 1, "Images much larger than displayed", "Images are sized sensibly",
    "Downloading a 3000px photo to show it 400px wide wastes mobile data and slows the page. We compare the image's real width with its displayed width.",
    "Resize or compress these images, or serve smaller versions with srcset."),
];

export const CHECK_BY_ID = Object.fromEntries(CHECKS.map((ch) => [ch.id, ch]));
